// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOmsRNEGoSCb7vUkhsEk98DWtU03IbkOQ',
    appId: '1:58516626621:web:d8661c8a65d6cad759ebd4',
    messagingSenderId: '58516626621',
    projectId: 'quirzy-bd6c3',
    authDomain: 'quirzy-bd6c3.firebaseapp.com',
    storageBucket: 'quirzy-bd6c3.firebasestorage.app',
    measurementId: 'G-KSLQ4XQXWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyupSqbHcx1SqefowFd7LTWhuCHU_MpTI',
    appId: '1:58516626621:android:002d1e84249db5aa59ebd4',
    messagingSenderId: '58516626621',
    projectId: 'quirzy-bd6c3',
    storageBucket: 'quirzy-bd6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSG0RGJVxceRS0scF1RDPkm0yGpWnTJ08',
    appId: '1:58516626621:ios:e634422a0c49fa6f59ebd4',
    messagingSenderId: '58516626621',
    projectId: 'quirzy-bd6c3',
    storageBucket: 'quirzy-bd6c3.firebasestorage.app',
    iosBundleId: 'com.example.quirzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSG0RGJVxceRS0scF1RDPkm0yGpWnTJ08',
    appId: '1:58516626621:ios:e634422a0c49fa6f59ebd4',
    messagingSenderId: '58516626621',
    projectId: 'quirzy-bd6c3',
    storageBucket: 'quirzy-bd6c3.firebasestorage.app',
    iosBundleId: 'com.example.quirzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOmsRNEGoSCb7vUkhsEk98DWtU03IbkOQ',
    appId: '1:58516626621:web:f048203d7e06e39259ebd4',
    messagingSenderId: '58516626621',
    projectId: 'quirzy-bd6c3',
    authDomain: 'quirzy-bd6c3.firebaseapp.com',
    storageBucket: 'quirzy-bd6c3.firebasestorage.app',
    measurementId: 'G-W1B4L10RYG',
  );
}
